# Generated by Django 5.2.7 on 2025-10-26 10:32

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the course/module, e.g., 'ISEF01'",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The text of the question.")),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation or background information for the question.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="The review status of the question.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: The course/module this question belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="quiz.course",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user who created this question.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_mode",
                    models.CharField(
                        choices=[("COOP", "Cooperative")],
                        default="COOP",
                        help_text="The game mode for this session.",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOBBY", "Lobby (Waiting for players)"),
                            ("ACTIVE", "Active (Game in progress)"),
                            ("FINISHED", "Ended (Show results)"),
                        ],
                        default="LOBBY",
                        help_text="The current status of the game session.",
                        max_length=10,
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        default=quiz.models.generate_join_code,
                        help_text="Unique code for players to join this game session.",
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The module from which questions will be drawn for this game session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.course",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current question being answered in the game session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quiz.question",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="game_sessions", to="quiz.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The text of the answer option.", max_length=500
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Indicates if this answer is correct."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question this answer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="The player's score in this game."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="quiz.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "session")},
            },
        ),
        migrations.CreateModel(
            name="TeamGameAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_answers",
                        to="quiz.question",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.answer"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_answers",
                        to="quiz.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "question")},
            },
        ),
    ]
