# Generated by Django 5.2.7 on 2025-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="If rejected, the reason for rejection.",
                null=True,
            ),
        ),
    ]
